#!/usr/bin/env node

'use strict';

var fs = require('fs'),
    path = require('path');

var pkg = require('../../package.json'),
    version = pkg.version,
    file = fs.readFileSync(path.resolve('lib/wheel-indicator.js'), 'utf-8'),
    versionInFile = file.match(/@version\s(\d.\d.\d)/)[1];

if (version !== versionInFile) {
    console.error('Version of banner and file are different');
    process.exit(1);
}
